database:
  storage: 'milvus'
  #storage: 'neo4j'
  config:
    # IVF_FLAT/HNSW
    index_type: "IVF_FLAT"  
    # L2/COSINE
    metric_type: "L2"   
    embeddings: "openai"     

agent:
  model:
    name: "gpt-4o-2024-11-20"
    temperature: 1

retrieval:
  algorithm: "self_rag"
  reranker:
    type: "RankLLMRerank"
    model: "gpt-4o-2024-11-20"
    top_n: 3    
    threshold: 0.3   
  compressor:
    type: "LLMChainExtractor"
    retriever: "ContextualCompressionRetriever"
    parameters:
      max_length: 256 
  retriever:
    # similarity_search/MMR
    type: "similarity_search"
    # similarity/hybrid/bm25'
    search_type: "similarity"
    params:
      k: 20
      ef: 30
  template: 
    rag: prompts/rag.yaml
    search: prompts/search.yaml
    extract: prompts/extract.yaml
  collection: "writeups"
  #collection: "neo4j"

features:
  hallucination_grading: False
  answer_grading: False
  retrieval_grading: False
  search_params: False
  rerank: False
  compressor: False
  multi_query: False
  rag_fusion: False
  decomposition: False
  step_back: False
  question_rewriting: False
  graph: False
  force_output: False
