database:
  storage: 'milvus'
  config:
    # IVF_FLAT/HNSW
    index_type: "IVF_FLAT"  
    # L2/COSINE
    metric_type: "L2"        

agent:
  model:
    type: "openai"
    name: "gpt-4o-2024-11-20"
    temperature: 1

retrieval:
  reranker:
    type: "RankLLMRerank"
    model: "gpt-4o-2024-11-20"
    top_n: 3    
    threshold: 0.3   
  compressor:
    type: "LLMChainExtractor"
    retriever: "ContextualCompressionRetriever"
    parameters:
      max_length: 256 
  retriever:
    # similarity_search/MMR
    type: "similarity_search"
    # similarity/hybrid/bm25'
    search_type: "similarity"
    params:
      k: 20
      ef: 30
  template: 
    rag_main: |
      You are an assistant for question-answering tasks.
      Use the following pieces of retrieved context to answer the question.
      If you don't know the answer, just say that you don't know.
      Use three sentences maximum and keep the answer concise.
      Question: {question}
      Context: {context}
      Answer:
    question: |
      You are an AI assistant specialized in generating queries for a Retrieval-Augmented Generation (RAG) system to solve Capture the Flag (CTF) challenges in cybersecurity. 
      Below is an observation from the conversation context describing the challenge or problem at hand. Your job is to formulate **a single query** that best retrieves relevant information or solutions from the RAG database. 
      Your query should:
      1. Reflect the key details from the **Observation**.
      2. Map to one (or more) of the common CTF categories: crypto, web exploitation, reverse engineering, binary exploitation (pwn), forensics, or miscellaneous.
      3. Be concise, clear, and specific—aimed at retrieving only the most helpful references or solution steps.
      Observation**:
      {observation}
      Output:
      Provide **only** the query text. Avoid explanations or additional commentary.
  collection: "HFCTF"

features:
  search_params: False
  rerank: False
  compressor: False
  multi_query: False
  rag_fusion: False
  decomposition: False
  step_back: False
