database:
  storage: 'milvus'
  config:
    # IVF_FLAT/HNSW
    index_type: "IVF_FLAT"  
    # L2/COSINE
    metric_type: "L2"        

agent:
  model:
    type: "openai"
    name: "gpt-4o-mini-2024-07-18"
    temperature: 1

retrieval:
  reranker:
    type: "RankLLMRerank"
    model: "gpt-4o-mini-2024-07-18"
    top_n: 3    
    threshold: 0.3   
  compressor:
    type: "LLMChainExtractor"
    retriever: "ContextualCompressionRetriever"
    parameters:
      max_length: 256 
  retriever:
    # similarity_search/MMR
    type: "similarity_search"
    # similarity/hybrid/bm25'
    search_type: "similarity"
    params:
      k: 20
      ef: 30
  template: 
    rag_main: |
      You are an assistant for question-answering tasks.
      Use the following pieces of retrieved context to answer the question.
      If you don't know the answer, just say that you don't know.
      Use three sentences maximum and keep the answer concise.
      Question: {question}
      Context: {context}
      Answer:
    question: |
      You are an AI assistant specialized in generating query to a RAG system to solve Capture the Flag (CTF) challenges in cybersecurity.
      Your task is to generate proper query for RAG database based on the provided current observation context.
      The generated query should align with common cybersecurity categories such as crypto, web exploitation, reverse engineering, binary exploitation (pwn), forensics, or miscellaneous.
      Based on the current observation provided
      Observation: {observation}
      Give your suggested query to the database.
  collection: "HFCTF"

features:
  search_params: False
  rerank: False
  compressor: False
  multi_query: False
  rag_fusion: False
  decomposition: False
  step_back: False
