context_to_task: |
  You are an expert at analyzing CTF (Capture The Flag) challenge solving contexts.
  Given the following conversation context (including thoughts and action outputs),
  determine if this context needs to be broken down into 1-3 subtasks.
  If the context can only be decomposed into single or fewer tasks, don't provide unncessary tasks.
  Your decompositon should be concise, you should focus only on helping another agent solve CTF Challenges.                                                                 
  Conversation Context:
  ```
  {context}
  ```
  Output Format:
  Return a JSON array of subtasks. If decomposition is not needed, return a single task that summarizes the main objective.
  Format: [{{"task": "Description of subtask 1"}}, {{"task": "Description of subtask 2"}}]
  Only return the JSON array, nothing else.
task_to_question: |
  You are an expert at identifying specific information needs for CTF (Capture The Flag) challenge tasks.
  Given the following task related to a CTF challenge, extract 1 key question that needs to be answered to complete this task.
  The question should be specific to the techniques, tools, or concepts mentioned in the task.
  Task:
  ```
  {task}
  ```
  Original Context (for reference):
  ```
  {context}
  ```
  Output Format:
  Return a single question that would help address this task.
  Make sure the question ends with a question mark.
  Only return the question text, nothing else.
question_evaluation: |
  Evaluate if the following question is suitable for the given CTF challenge context.
  Task: {task}
  Question: {question}
  Original Context:
  ```
  {context}
  ```
  Consider these criteria:
  1. Is the question relevant to the task and context?
  2. Is the question specific enough to yield useful information?
  3. Is the question focused on technical aspects needed to solve the challenge?
  4. Does the context indicate that this information is actually needed?
  Return a JSON object with the following structure:
  {{
    "is_suitable": true/false,
    "reason": "Brief explanation of your evaluation"
  }}
  Only return the JSON object, nothing else.
answer_evaluation: |
  You are evaluating if an answer to a CTF challenge question contains actually useful information.
  Be STRICT in your evaluation - answers must provide SPECIFIC, TECHNICAL information to be considered relevant.
  Task: {task}
  Question: {question}
  Answer: {answer}
  First, check if any of these NON-INFORMATIVE patterns are present:
  1. "I don't know" or "I'm not sure" or similar disclaimers
  2. Vague, general statements that don't address the specific technical question
  3. Responses that only restate the question without adding technical details
  4. Generic explanations that could apply to any CTF challenge
  5. Empty promises of information without actually providing it
  An answer is only RELEVANT if it contains AT LEAST ONE of the following:
  1. Specific technical details directly related to the question (not just general concepts)
  2. Named tools, commands, or techniques that could be applied to the task
  3. Concrete exploitation methods or vulnerability details
  4. Code snippets, payloads, or specific syntax that could be used
  5. Step-by-step instructions that are specific to the task
  Return a JSON object with the following structure:
  {{
    "is_relevant": false,  // Default to false unless proven otherwise
    "reason": "Detailed explanation of why the answer is or is not relevant"
  }}
  Only return the JSON object, nothing else.
fallback_with_task:
  question: f"What techniques are needed for this CTF task?",
  evaluation: "Fallback question due to processing error"
fallback_no_task:
  task: "Understand the CTF challenge"
  question: "What is the main vulnerability or technique needed for this CTF challenge?"
  evaluation: "Fallback question when no tasks could be processed"
